winos:
	g++ main.cpp -std=c++11 -o main -Wall -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
macos:
	g++ main.cpp -std=c++11 -o main -Wall -I/opt/homebrew/include -D_THREAD_SAFE -L/opt/homebrew/lib -lsfml-window -lsfml-graphics -lsfml-system -lsfml-audio